"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const main_1 = require("./electron/main");
const ai_handlers_1 = require("./electron/handlers/ai-handlers");
const app_handlers_1 = require("./electron/handlers/app-handlers");
const file_handlers_1 = require("./electron/handlers/file-handlers");
const file_watcher_1 = require("./electron/utils/file-watcher");
const fileWatcher = (0, file_watcher_1.setupFileWatcher)(main_1.getMainWindow, ai_handlers_1.getChangedFiles);
(0, ai_handlers_1.setupAIHandlers)(fileWatcher.rebuildAfterClaudeFinished);
(0, app_handlers_1.setupAppHandlers)(main_1.getMainWindow);
(0, file_handlers_1.setupFileHandlers)(main_1.getMainWindow);
